2016-08-09 01:50:59,608 - streamparse.stdout - INFO - Could not create or no need to re-create tcount
2016-08-09 01:51:00,081 - streamparse.stdout - INFO - Could not create or no need to re-create tcount
2016-08-09 01:51:00,176 - streamparse.stdout - INFO - No need to create table
2016-08-09 01:51:00,291 - streamparse.stdout - INFO - Could not create or no need to re-create tcount
2016-08-09 01:51:00,462 - streamparse.stdout - INFO - No need to create table
2016-08-09 01:51:00,648 - streamparse.stdout - INFO - Could not create or no need to re-create tcount
2016-08-09 01:51:01,018 - streamparse.stdout - INFO - No need to create table
2016-08-09 01:51:01,299 - streamparse.storm.component - ERROR - Exception in WordCounter.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/storm/component.py", line 489, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/storm/bolt.py", line 219, in _run
    self.process(tup)
  File "bolts/wordcount.py", line 60, in process
    cur.execute("""UPDATE tweetwordcount SET count=%s WHERE word=%s;""",(self.counts[uWord], uWord))
InternalError: current transaction is aborted, commands ignored until end of transaction block

